site/src/Entity/BikerParcel.php
<?php

namespace App\Entity;

use App\Repository\BikerParcelRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Parcel;

#[ORM\Entity(repositoryClass: BikerParcelRepository::class)]
class BikerParcel
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $pick_up_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $drop_off_at = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\ManyToOne(targetEntity : "Parcel")]
    #[ORM\JoinColumn(nullable:false)]
    private ?Parcel $parcel;

    #[ORM\ManyToOne(targetEntity : "Biker")]
    #[ORM\JoinColumn(nullable:false)]
    private ?Biker $biker;    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPickUpAt(): ?\DateTimeInterface
    {
        return $this->pick_up_at;
    }

    public function setPickUpAt(\DateTimeInterface $pick_up_at): self
    {
        $this->pick_up_at = $pick_up_at;

        return $this;
    }

    public function getDropOffAt(): ?\DateTimeInterface
    {
        return $this->drop_off_at;
    }

    public function setDropOffAt(\DateTimeInterface $drop_off_at): self
    {
        $this->drop_off_at = $drop_off_at;

        return $this;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getParcel(): ?Parcel
    {
        return $this->parcel;
    }

    public function setParcel(?Parcel $parcel):Self
    {
        $this->parcel = $parcel;

        return $this;
    }

    public function getBiker(): ?Biker
    {
        return $this->biker;
    }

    public function setBiker(?Biker $biker):Self
    {
        $this->biker = $biker;

        return $this;
    }    

    public function __toString()
    {
        return $this->getStatus();
    }
}

site/src/Controller/TodoController.php
<?php

namespace App\Controller;

use App\Service\TodoService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class TodoController extends AbstractController
{
    private $security;
    private $todoService;
    public function __construct(Security $security, TodoService $todoService)
    {
        $this->security = $security;
        $this->todoService = $todoService;
    }

    #[Route('/api/todo', name: 'app_todo')]
    public function index()
    {
        [$parcels, $bikerParcelsCompleted, $bikerParcelsPending, $unassignedParcels] = $this->todoService->getTodos();

        return $this->render('todo/index.html.twig', [
            'parcels' => $parcels,
            'bikerParcelsCompleted' => $bikerParcelsCompleted,
            'bikerParcelsPending' => $bikerParcelsPending,
            'unassignedParcels' => $unassignedParcels
        ]);
    }

    #[Route('/api/todo/create', name: 'app_create_todo', methods: ['POST'])]
    public function create(Request $request):Response
    {
        try {
            $user = $this->security->getUser();
            $this->todoService->createTodo($request, $user);

            return new Response("Parcel Assigned TO You Successfully", 200);      
        } catch (NotFoundHttpException $exception) {
            return new Response($exception->getMessage(), 200);      
        }
    }  
}

site/templates/todo/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Login!{% endblock %}

{% block body %}
<section>
  <div class="container">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-12 col-xl-10">

        <div class="card">
          <div class="card-header p-3">
            <h3 class="mb-0"><i class="fas fa-tasks me-2"></i>Parcels List</h3>
          </div>
          <div class="card-body" data-mdb-perfect-scrollbar="true">

            <table class="table mb-0">
              <thead>
                <tr>
                    <th colspan="8" style="text-align:center;"><h3>Completed Todos</h3></th>                            
                </tr>                
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Title</th>
                    <th scope="col">Pick-up</th>
                    <th scope="col">Drop-off</th>
                    <th scope="col">Status</th>
                    <th scope="col">Biker Name</th>
                    <th scope="col">Pick Up At</th>
                    <th scope="col">Drop Off At</th>     
                    <th scope="col">Actions</th>                                 
                </tr>
              </thead>
              <tbody>
                {% for parcel in parcels %}
                  {% for bikerParcel in bikerParcelsCompleted %}
                    {% if(parcel == bikerParcel.parcel and bikerParcel.status == "done") %}
                      <tr class="fw-normal">
                        <th>
                          <span class="ms-2">{{ parcel.id }}</span>
                        </th>
                        <th>
                          <span class="ms-2">{{ parcel.title }}</span>
                        </th>
                        <td class="align-middle">
                          <span>{{ parcel.pick_up }}</span>
                        </td>
                        <td class="align-middle">
                          <span>{{ parcel.drop_off }}</span>
                        </td>
                        <td class="align-middle">
                          <span>{{ bikerParcel.status }}</span>
                        </td>                  
                        <td class="align-middle">
                          <span>{{ bikerParcel.biker.id }}</span>
                        </td>              
                        <td class="align-middle">
                          <span>{{ bikerParcel.pickUpAt|date('d-m-Y h:i:s') }}</span>
                        </td>              
                        <td class="align-middle">
                          <span>{{ bikerParcel.dropOffAt|date('d-m-Y h:i:s') }}</span>
                        </td>                                                      
                        <td class="align-middle">
                          <button class="parcel btn" data-id="{{ parcel.id }}" {% if(parcel.id == bikerParcel.parcel.id) %} disabled {% endif %}> Accept</button>
                        </td>                                                      
                      </tr>
                    {% endif %}
                  {% endfor %}
                {% endfor %}     
              </tbody>
            </table>
            <table class="table mb-0">
              <thead>
                <tr>
                    <th colspan="8" style="text-align:center;"><h3>Pending Todos</h3></th>                            
                </tr>                
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Title</th>
                    <th scope="col">Pick-up</th>
                    <th scope="col">Drop-off</th>
                    <th scope="col">Status</th>
                    <th scope="col">Biker Name</th>
                    <th scope="col">Pick Up At</th>
                    <th scope="col">Drop Off At</th>     
                    <th scope="col">Actions</th>                                 
                </tr>
              </thead>
              <tbody>
                {% for parcel in parcels %}
                  {% for bikerParcel in bikerParcelsPending|filter(bikerParcel => parcel.id == bikerParcel.parcel.id) %}
                      <tr class="fw-normal">
                        <th>
                          <span class="ms-2">{{ parcel.id }}</span>
                        </th>                      
                        <th>
                          <span class="ms-2">{{ parcel.title }}</span>
                        </th>
                        <td class="align-middle">
                          <span>{{ parcel.pick_up }}</span>
                        </td>
                        <td class="align-middle">
                          <span>{{ parcel.drop_off }}</span>
                        </td>
                        <td class="align-middle">
                          <span>{{ bikerParcel.status }}</span>
                        </td>                  
                        <td class="align-middle">
                          <span>{{ bikerParcel.biker.id }}</span>
                        </td>              
                        <td class="align-middle">
                          <span>{{ bikerParcel.pickUpAt|date('d-m-Y h:i:s') }}</span>
                        </td>              
                        <td class="align-middle">
                          <span>{{ bikerParcel.dropOffAt|date('d-m-Y h:i:s') }}</span>
                        </td>                                                      
                        <td class="align-middle">
                          <button class="parcel btn" data-id="{{ parcel.id }}" {% if(parcel.id == bikerParcel.parcel.id) %} disabled {% endif %}> Accept</button>
                        </td>                                                      
                      </tr>
                  {% endfor %}
                {% endfor %}                                
              </tbody>
            </table>
            <table class="table mb-0">
              <thead>
                <tr>
                    <th colspan="8" style="text-align:center;"><h3>Unassigned Todos</h3></th>                            
                </tr>                
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Title</th>
                    <th scope="col">Pick-up</th>
                    <th scope="col">Drop-off</th>
                    <th scope="col">Status</th>
                    <th scope="col">Biker Name</th>
                    <th scope="col">Pick Up At</th>
                    <th scope="col">Drop Off At</th>     
                    <th scope="col">Actions</th>                                 
                </tr>
              </thead>
              <tbody>
                {% for parcel in unassignedParcels %}
                      <tr class="fw-normal">
                        <th>
                          <span class="ms-2">{{ parcel.parcel.id ?? parcel.id }}</span>
                        </th>
                        <th>
                          <span class="ms-2">{{ parcel.parcel.title ?? parcel.title }}</span>
                        </th>
                        <td class="align-middle">
                          <span>{{ parcel.parcel.pick_up ?? parcel.pick_up }}</span>
                        </td>
                        <td class="align-middle">
                          <span>{{ parcel.parcel.drop_off ?? parcel.drop_off}}</span>
                        </td>
                        <td class="align-middle">
                          <span></span>
                        </td>                  
                        <td class="align-middle">
                          <span></span>
                        </td>              
                        <td class="align-middle">
                          <span></span>
                        </td>              
                        <td class="align-middle">
                          <span></span>
                        </td>                                                      
                        <td class="align-middle">
                          <button class="parcel btn" data-id="{{ parcel.parcel.id ?? parcel.id }}"> Accept</button>
                        </td>                                                      
                      </tr>
                {% endfor %}                                
              </tbody>
            </table>            
          </div>
        </div>

      </div>
    </div>
  </div>
</section>
<script src="{{ asset('js/todo.js') }}?version={{random(1,4)}}"></script>
{% endblock %}